-- Generated by npm run generate; do not edit manually.
WowheadQuestCommentsDB = {
    [14435] = {
        {
            id = 1076063,
            score = 265,
            author = "533061",
            text = "Try not to bolt off when you pick up the quest, use the disguise right next to the quest giver and fireplace and the mage will teleport you to the quest area. Hoofing it to the quest area will not let you use the disguise.",
            date = "2010-07-08T12:19:11-05:00",
            sourceUrl = "https://www.wowhead.com/quest=14435#comments:id=1076063",
        },
        {
            id = 1191489,
            score = 51,
            author = "Dradee",
            text = "This quest is hilarious. Seriously. Read the stuff you can say to Ungarl, read his responses too, and you will not regret it.",
            date = "2010-11-27T20:07:45-06:00",
            sourceUrl = "https://www.wowhead.com/quest=14435#comments:id=1191489",
        },
        {
            id = 1799093,
            score = 28,
            author = "WokkaD",
            text = "Notes :\n1. this is a timed quest. You have 2 hours to complete it after ACCEPTING.\n2. the robes have a 2 hour life. If they stay in your bag for 2 hours, they will disappear.\n3. Do not log out or do any other quest or exploration.\n4. this quest should take about 15 mins to complete.\n5. for those who do NOT have Timbermaw Hold rep, don't worry. This quest does not create a TH rep status / bar.\n6. you will meet them again in Felwood, where you can gain rep with them.\n7. i think that the last statement on the first page went directly to the last page which includes \"\". Be ready to defend yourself when you get to the \"belly button\" page.\n8. as a Goblin Hunter, my pet was on \"assist\". It did not attack until i was attacked.\n9. the disguise will re-appear in your bags when you leave the hold.\n10. the way out is UP the ramp / stairs to the right of the Chieftan , over the smooth bridge, taking the left fork on the bridge.\n11. no need to farm within the hold. There are 4 of each on the way out.",
            date = "2013-01-15T15:33:35-06:00",
            sourceUrl = "https://www.wowhead.com/quest=14435#comments:id=1799093",
        },
        {
            id = 1284502,
            score = 22,
            author = "Delvara",
            text = "Am I the only one who would really like to see the Timbermaw join the alliance?\n\nI think it would be really awesome.",
            date = "2011-01-08T17:08:15-06:00",
            sourceUrl = "https://www.wowhead.com/quest=14435#comments:id=1284502",
        },
        {
            id = 1191678,
            score = 13,
            author = "711687",
            text = "You will want to turn this in before the disguise disappears from your bags. I completed all the quest objectives and had to log off before turning the quest in... came back on later and could not turn it in because I no longer had the disguise. Since I couldn't get a new disguise from either of the NPCs, I had to abandon the quest and re-do it again.",
            date = "2010-11-27T21:39:12-06:00",
            sourceUrl = "https://www.wowhead.com/quest=14435#comments:id=1191678",
        },
    },
}
